version: "3"

services:
  user-core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    networks:
      - services
    volumes:
      - type: bind
        source: .
        target: /src
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - user-db
    command: npm start

  user-db:
    image: postgres
    restart: always
    networks:
      - services
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
networks:
  services:
    name: services
    external: true