name: deploy
on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: jonasearth/${{ secrets.SERVICE_NAME }}
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push amd64
      id: build-amd64
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        target: amd64
        platforms: linux/amd64
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Build and push arm64
      id: build-arm64
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        target: arm64
        platforms: linux/arm64
    - name: Create Manifest
      uses: int128/docker-manifest-create-action@v2
      id: build
      with:
        tags: ${{ steps.meta.outputs.tags }}
        sources: |
          docker.io/${{ github.repository }}@${{ steps.build-amd64.outputs.digest }}
          docker.io/${{ github.repository }}@${{ steps.build-arm64.outputs.digest }}
    
  
  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create kubeconfig
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        mkdir ${HOME}/.kube
        echo "$KUBE_CONFIG" > ${HOME}/.kube/config
        echo "$KUBE_CONFIG"
    - name: Deploy to K8s
      run: helm upgrade --install ${{ secrets.SERVICE_NAME }} ./deployment/helm --namespace dev --kube-insecure-skip-tls-verify